version: "3.3"

services:
  txtrackingapi:
    image: nearfoundation/txtrackingapi:local
    build:
      context: ./
      dockerfile: ./backend/docker/Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
      # Remember to use NODE_ENV=production if you're using mainnet (so that the appropriate explorerUrl gets used in the frontend)
      - REACT_APP_ENVIRONMENT=development
      - MONGO=mongodb://mongodb:27017/
      - MONGODB_PASSWORD=
      - REACT_APP_ALLOW_DELETING_FROM_DATABASE="false"
      - NODE_ENV=test
      - POSTGRESQL_CONNECTION_STRING=postgresql://pguser:pgpass@postgres:5432/tta_db_local
    depends_on:
      - postgres
      - mongodb
    ports:
      - 8086:8086
  txtrackingui:
    image: nearfoundation/txtrackingui:local
    build:
      context: ./
      dockerfile: ./frontend/docker/Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8086
      # Remember to use NODE_ENV=production if you're using mainnet (so that the appropriate explorerUrl gets used in the frontend)
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_ALLOW_DELETING_FROM_DATABASE="false"
    ports:
      - 8085:8085
    depends_on:
      - txtrackingapi
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: tta_db_local
  mongodb:
    image: mongo:5.0.2
    restart: always
    environment:
      - MONGODB_USER=mongouser
      - MONGODB_PASSWORD=mongopass
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 27017:27017
      #- "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"
    volumes:
      - db:/data/db

volumes:
  db:
